name: 'TODO Registrar'
description: 'Find TODO comments in code and create issues in issue tracker using todo-registrar'
author: 'Aeliot-Tm'

branding:
  icon: 'check-square'
  color: 'blue'

inputs:
  check_opened:
    description: 'Check for open pull requests before running. If open PRs exist, skip processing'
    required: false
    default: 'true'
  config:
    description: 'Inline YAML configuration (used when config_path is not set)'
    required: false
    default: ''
  config_path:
    description: 'Path to configuration file (relative to workspace)'
    required: false
    default: ''
  env_vars:
    description: 'Environment variable names to pass to container (newline or space separated)'
    required: false
    default: ''
  new_branch_name:
    description: 'Name of new branch to create for changes. If empty - stay on current branch'
    required: false
    default: ''
  target_branch_name:
    description: 'Target branch for pull request. If empty - use current branch'
    required: false
    default: ''
  user_email:
    description: 'Git user email for commits'
    required: false
    default: 'action@github.com'
  user_name:
    description: 'Git user name for commits'
    required: false
    default: 'GitHub Action'
  verbosity:
    description: 'Verbosity level: quiet, normal, verbose, very-verbose, debug'
    required: false
    default: 'normal'

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ -z "${{ inputs.config_path }}" && -z "${{ inputs.config }}" ]]; then
          echo "::error::Either 'config_path' or 'config' input must be provided"
          exit 1
        fi

    - name: Map verbosity to flag
      id: verbosity
      shell: bash
      run: |
        VERBOSITY="${{ inputs.verbosity }}"
        VERBOSITY="${VERBOSITY:-normal}"

        case "$VERBOSITY" in
          quiet)
            echo "flag=-q" >> $GITHUB_OUTPUT
            ;;
          normal)
            echo "flag=" >> $GITHUB_OUTPUT
            ;;
          verbose)
            echo "flag=-v" >> $GITHUB_OUTPUT
            ;;
          very-verbose)
            echo "flag=-vv" >> $GITHUB_OUTPUT
            ;;
          debug)
            echo "flag=-vvv" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "::error::Invalid verbosity level: $VERBOSITY. Valid values: quiet, normal, verbose, very-verbose, debug"
            exit 1
            ;;
        esac

    - name: Build environment flags
      id: env_flags
      shell: bash
      run: |
        ENV_FLAGS=""
        ENV_VARS="${{ inputs.env_vars }}"

        if [[ -n "$ENV_VARS" ]]; then
          # Replace newlines with spaces and split
          for VAR_NAME in $ENV_VARS; do
            # Skip empty entries
            [[ -z "$VAR_NAME" ]] && continue
            # Add -e flag for each variable
            ENV_FLAGS="$ENV_FLAGS -e $VAR_NAME"
          done
        fi

        echo "flags=$ENV_FLAGS" >> $GITHUB_OUTPUT

    - name: Determine branches for PR
      id: branches
      shell: bash
      run: |
        NEW_BRANCH="${{ inputs.new_branch_name }}"
        TARGET_BRANCH="${{ inputs.target_branch_name }}"
        # Get current branch if not specified
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        if [[ -z "$NEW_BRANCH" ]]; then
          NEW_BRANCH="$CURRENT_BRANCH"
        fi
        if [[ -z "$TARGET_BRANCH" ]]; then
          TARGET_BRANCH="$CURRENT_BRANCH"
        fi
        echo "current_branch=$CURRENT_BRANCH" >> $GITHUB_OUTPUT
        echo "new_branch=$NEW_BRANCH" >> $GITHUB_OUTPUT
        echo "target_branch=$TARGET_BRANCH" >> $GITHUB_OUTPUT
        if [[ "$NEW_BRANCH" != "$TARGET_BRANCH" ]]; then
          echo "should_create_pr=true" >> $GITHUB_OUTPUT
        else
          echo "should_create_pr=false" >> $GITHUB_OUTPUT
        fi

    - name: Check for open pull requests and branch status
      id: check_prs
      if: inputs.check_opened == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        # Default: don't skip processing
        echo "skip_processing=false" >> $GITHUB_OUTPUT

        # Check for open PRs
        if [[ "${{ steps.branches.outputs.should_create_pr }}" == "true" ]]; then
          OPEN_PRS=$(gh pr list --state open \
            --head "${{ steps.branches.outputs.new_branch }}" \
            --base "${{ steps.branches.outputs.target_branch }}" \
            --json number --jq length)
          if [[ "$OPEN_PRS" -gt 0 ]]; then
            echo "skip_processing=true" >> $GITHUB_OUTPUT
            echo "::notice::Found $OPEN_PRS open PR(s) from '${{ steps.branches.outputs.new_branch }}' to '${{ steps.branches.outputs.target_branch }}'. Skipping processing."
            exit 0
          fi
        fi

        # Check if behind remote
        if [[ "${{ steps.branches.outputs.new_branch }}" != "${{ steps.branches.outputs.current_branch }}" ]]; then
          git fetch origin --quiet
          NEW_BRANCH="${{ steps.branches.outputs.new_branch }}"
          if git show-ref --verify --quiet refs/remotes/origin/$NEW_BRANCH; then
            BEHIND=$(git rev-list --count HEAD..origin/$NEW_BRANCH)
            if [[ "$BEHIND" -gt 0 ]]; then
              echo "skip_processing=true" >> $GITHUB_OUTPUT
              echo "::notice::Remote branch 'origin/$NEW_BRANCH' is $BEHIND commit(s) ahead of current HEAD. Skipping processing."
            fi
          fi
        fi

    - name: Compose config path
      id: config
      if: steps.check_prs.outputs.skip_processing != 'true'
      shell: bash
      run: |
        if [[ -n "${{ inputs.config_path }}" ]]; then
          echo "path=/code/${{ inputs.config_path }}" >> $GITHUB_OUTPUT
        else
          echo "path=STDIN" >> $GITHUB_OUTPUT
        fi

    - name: Run TODO Registrar
      if: steps.check_prs.outputs.skip_processing != 'true'
      shell: bash
      run: |
        echo '${{ inputs.config }}' | docker run --rm -i \
          -v "${{ github.workspace }}:/code" \
          ${{ steps.env_flags.outputs.flags }} \
          ghcr.io/aeliot-tm/todo-registrar:v3.0.0 \
          ${{ steps.verbosity.outputs.flag }} \
          --config="${{ steps.config.outputs.path }}"

    - name: Checkout new branch
      if: steps.check_prs.outputs.skip_processing != 'true' && steps.branches.outputs.new_branch != steps.branches.outputs.current_branch
      shell: bash
      run: git checkout -b ${{ steps.branches.outputs.new_branch }} 1> /dev/null

    - name: Commit and push changes
      id: commit
      if: steps.check_prs.outputs.skip_processing != 'true'
      shell: bash
      run: |
        git config --local user.email "${{ inputs.user_email }}"
        git config --local user.name "${{ inputs.user_name }}"
        git add -A .

        if git commit -m "TODO-REGISTRAR: automated registering of new TODOs"; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
          git push origin HEAD
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "Nothing to commit" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Create pull request
      if: steps.check_prs.outputs.skip_processing != 'true' && steps.branches.outputs.should_create_pr == 'true' && steps.commit.outputs.has_changes == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh pr create \
          -B ${{ steps.branches.outputs.target_branch }} \
          -H ${{ steps.branches.outputs.new_branch }} \
          --title '[TODO Registrar] automated registering of new TODOs' \
          --body 'Created by Github action'
